[font]
normal = { family = "MesloLGS NF", style = "Regular" }
bold = { family = "MeslOLGS NF", style = "Bold" }
italic = { family = "MeslOLGS NF", style = "Italic" }
bold_italic = { family = "MeslOLGS NF", style = "Bold Italic" }
size = 12.0


[window]
opacity = 1
blur = true

[general]
import = [
    "~/.config/alacritty/themes/groob.toml"
]
