import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[font]
normal = { family = "Inconsolata Nerd Font Mono", style = "Regular" }
bold = { family = "Inconsolata Nerd Font Mono", style = "Bold" }
italic = { family = "Inconsolata Nerd Font Mono", style = "Italic" }
bold_italic = { family = "Inconsolata Nerd Font Mono", style = "Bold Italic" }
size = 12.0  # Adjust the size as needed


[window]
opacity = 0.8
blur = true
