layerrule {
    name=waybar
    match:namespace=waybar
    blur=on
}

windowrule {
    name=spotify
    match:class=Spotify
    workspace=9
    no_initial_focus=on

}

windowrule {
    name=steam
    match:class=steam
    workspace=4
}

windowrule {
    name=discord
    match:class=discord
    workspace=8
}

windowrule {
    name=pavu
    match:class=org.pulseaudio.pavucontrol
    size=(monitor_w*0.35) (monitor_h*0.5)
    move=(monitor_w-window_w-2) 32
    float=on

}

# Ignore maximize requests from apps
windowrule {
    name=supress
    match:class=.*
    suppress_event=maximize
}
