layerrule = blur, waybar

# Steam
windowrule = workspace 4,float,class:^(steam)$

# Spotify
windowrule = workspace 9,class:^(Spotify)$

# Discord
windowrule = workspace 8,class:^(discord)$

# Pavucontrol
windowrule = float, class:^(org.pulseaudio.pavucontrol)$
windowrule = size 35% 50%, class:^(org.pulseaudio.pavucontrol)$
windowrulev2 = move 100%-w-2 32, class:^(org\.pulseaudio\.pavucontrol)$


windowrule = float, class:^(blueman-manager)$
windowrule = size 45% 75%, class:^(blueman-manager)$
windowrulev2 = center, class:^(blueman-manager)$

# Ignore maximize requests from apps
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
