foreground            #c4b8b8
background            #0c0a0a
cursor                #9e9494
cursor_text_color     #0c0a0a
selection_foreground  #0c0a0a
selection_background  #8a4060

color0   #2a2525
color8   #3d3636
color1   #8a4040
color9   #b05050
color2   #2e7060
color10  #3a9070
color3   #8a5c20
color11  #b07830
color4   #4a607a
color12  #5a7090
color5   #8a4060
color13  #b05880
color6   #2a8070
color14  #309088
color7   #5c5050
color15  #7a6f6f

background_opacity 0.8

font_family      JetBrainsMono Nerd Font Mono
font_size 12.0
bold_font        auto
italic_font      auto
bold_italic_font auto

force_ltr no
disable_ligatures always
