input {
    kb_layout = gb
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =
    follow_mouse = 1
    accel_profile = flat
}

cursor {
    default_monitor = DP-2
    persistent_warps = true
    inactive_timeout = 10
}

device {
    name = logitech-g303-1
    accel_profile = flat
    sensitivity = -0.2
}

ecosystem {
    no_update_news = true
    no_donation_nag = true

}

