local c = require("themes.groob.colors").dark
local cfg = require("themes.groob.config").config
local M = {}

local function set_terminal_colors()
	vim.g.terminal_color_0 = c.black
	vim.g.terminal_color_1 = c.red
	vim.g.terminal_color_2 = c.green
	vim.g.terminal_color_3 = c.yellow
	vim.g.terminal_color_4 = c.blue
	vim.g.terminal_color_5 = c.magenta
	vim.g.terminal_color_6 = c.cyan
	vim.g.terminal_color_7 = c.white
	vim.g.terminal_color_8 = c.bright_black
	vim.g.terminal_color_9 = c.bright_red
	vim.g.terminal_color_10 = c.bright_green
	vim.g.terminal_color_11 = c.bright_yellow
	vim.g.terminal_color_12 = c.bright_blue
	vim.g.terminal_color_13 = c.bright_magenta
	vim.g.terminal_color_14 = c.bright_cyan
	vim.g.terminal_color_15 = c.bright_white
	vim.g.terminal_color_background = c.bg
	vim.g.terminal_color_foreground = c.fg
end

local function set_groups()
	local hl = {
		Comment = { fg = c.gray05 },
		Constant = { fg = c.cyan },
		String = { fg = c.green },
		Character = { fg = c.green },
		Number = { fg = c.magenta },
		Boolean = { fg = c.yellow },
		Float = { fg = c.magenta },
		Identifier = { fg = c.fg },
		Function = { fg = c.white },
		Statement = { fg = c.white },
		Conditional = { fg = c.blue },
		Repeat = { fg = c.blue },
		Label = { fg = c.blue },
		Operator = { fg = c.yellow },
		Keyword = { fg = c.blue },
		PreProc = { fg = c.cyan },
		Include = { fg = c.blue },
		Define = { fg = c.cyan },
		Macro = { fg = c.cyan },
		PreCondit = { fg = c.cyan },
		Type = { fg = c.bright_blue },
		StorageClass = { fg = c.yellow },
		Structure = { fg = c.yellow },
		Typedef = { fg = c.yellow },
		Special = { fg = c.blue },
		SpecialChar = { fg = c.yellow },
		Tag = { fg = c.yellow },
		SpecialComment = { fg = c.gray05 },
		Debug = { fg = c.yellow },
		Underlined = { underline = true },
		Error = { fg = c.red },
		Todo = { fg = c.magenta },

		ColorColumn = { bg = c.gray01 },
		Conceal = { fg = c.gray06 },
		Cursor = { fg = c.black, bg = c.fg },
		lCursor = { fg = c.black, bg = c.fg },
		CursorIM = { fg = c.black, bg = c.fg },
		CursorLine = { bg = c.gray03 },
		Directory = { fg = c.blue },
		DiffAdd = { bg = c.green, fg = c.black },
		DiffChange = { fg = c.yellow, underline = true },
		DiffDelete = { bg = c.red, fg = c.black },
		DiffText = { bg = c.yellow, fg = c.black },
		EndOfBuffer = { fg = c.gray04, bg = cfg.transparent and c.none or c.bg },
		ErrorMsg = { fg = c.red },
		VertSplit = { fg = c.gray02 },
		WinSeparator = { fg = c.gray02 },
		Folded = { fg = c.gray04 },
		FoldColumn = { bg = cfg.transparent and c.none or c.bg, fg = c.gray05 },
		SignColumn = { bg = cfg.transparent and c.none or c.bg, fg = c.gray05 },
		IncSearch = { fg = c.black, bg = c.yellow },
		CurSearch = { fg = c.black, bg = c.yellow },
		LineNr = { fg = c.gray04 },
		CursorLineNr = { fg = c.gray06 },
		MatchParen = { fg = c.yellow, underline = true },
		ModeMsg = { fg = c.gray03, bold = true },
		MoreMsg = { fg = c.bright_magenta },
		NonText = { fg = c.gray05 },
		Normal = { fg = c.fg, bg = cfg.transparent and c.none or c.bg },
		NormalNC = { fg = c.fg, bg = cfg.transparent and c.none or c.bg_dark },
		NormalFloat = { fg = c.fg, bg = cfg.transparent and c.none or c.gray00 },
		FloatBorder = { fg = c.gray03, bg = c.bg },
		Pmenu = { fg = c.white, bg = c.black },
		PmenuSel = { fg = c.bright_white, bg = c.gray03 },
		PmenuSbar = { bg = c.gray02 },
		PmenuThumb = { bg = c.gray03 },
		Question = { fg = c.blue },
		QuickFixLine = { fg = c.cyan, bg = c.gray02 },
		Search = { fg = c.bright_yellow, bg = c.black },
		SpellBad = { fg = c.red, underline = true },
		SpellCap = { fg = c.yellow },
		SpellLocal = { fg = c.yellow },
		SpellRare = { fg = c.yellow },
		StatusLine = { fg = c.cyan, bg = cfg.transparent and c.none or c.gray01 },
		StatusLineNC = { fg = c.cyan, bg = cfg.transparent and c.none or c.gray01 },
		StatusLineTerm = { fg = c.white, bg = c.gray01 },
		StatusLineTermNC = { fg = c.gray05 },
		TabLine = { fg = c.gray05 },
		TabLineFill = { bg = c.black },
		TabLineSel = { fg = c.white },
		Terminal = { fg = c.fg, bg = c.black },
		Title = { fg = c.green },
		Visual = { fg = c.fg, bg = c.gray02 },
		VisualNOS = { bg = c.gray02 },
		WarningMsg = { fg = c.yellow },
		WildMenu = { fg = c.black, bg = c.blue },
		Winbar = { fg = c.white, bg = c.gray01 },
		WinbarNC = { fg = c.gray05, bg = c.bg_dark },

		htmlArg = { fg = c.bright_blue, italic = true },
		htmlEndTag = { fg = c.gray06 },
		htmlTitle = { fg = c.gray07 },
		htmlTag = { fg = c.gray06 },
		htmlTagN = { fg = c.gray06 },
		htmlTagName = { fg = c.cyan },

		markdownH1 = { fg = c.bright_blue, bold = true },
		markdownH2 = { fg = c.bright_blue, bold = true },
		markdownH3 = { fg = c.bright_blue, bold = true },
		markdownH4 = { fg = c.bright_blue, bold = true },
		markdownH5 = { fg = c.bright_blue, bold = true },
		markdownH6 = { fg = c.bright_blue, bold = true },
		markdownHeadingDelimiter = { fg = c.gray05 },
		markdownHeadingRule = { fg = c.gray05 },
		markdownId = { fg = c.cyan },
		markdownIdDeclaration = { fg = c.blue },
		markdownIdDelimiter = { fg = c.cyan },
		markdownLinkDelimiter = { fg = c.gray05 },
		markdownLinkText = { fg = c.blue, italic = true },
		markdownListMarker = { fg = c.gray05 },
		markdownOrderedListMarker = { fg = c.gray05 },
		markdownRule = { fg = c.gray05 },
		markdownUrl = { fg = c.green, bg = c.none },
		markdownBlockquote = { fg = c.gray07 },
		markdownBold = { fg = c.fg, bg = c.none, bold = true },
		markdownItalic = { fg = c.fg, bg = c.none, italic = true },
		markdownCode = { fg = c.yellow },
		markdownCodeBlock = { fg = c.yellow },
		markdownCodeDelimiter = { fg = c.gray05 },

		["@boolean"] = { fg = c.yellow },
		["@constructor"] = { fg = c.gray06 },
		["@constant.builtin"] = { fg = c.yellow },
		["@keyword.function"] = { fg = c.cyan },
		["@namespace"] = { fg = c.cyan, italic = true },
		["@parameter"] = { fg = c.magenta },
		["@property"] = { fg = c.gray07 },
		["@punctuation"] = { fg = c.gray06 },
		["@punctuation.delimiter"] = { fg = c.gray06 },
		["@punctuation.bracket"] = { fg = c.gray06 },
		["@punctuation.special"] = { fg = c.gray06 },
		["@string.documentation"] = { fg = c.green },
		["@string.regex"] = { fg = c.blue },
		["@string.escape"] = { fg = c.magenta },
		["@symbol"] = { fg = c.yellow },
		["@tag"] = { fg = c.cyan },
		["@tag.attribute"] = { fg = c.bright_blue, italic = true },
		["@tag.delimiter"] = { fg = c.gray06 },
		["@type.builtin"] = { fg = c.magenta },
		["@variable"] = { fg = c.fg },
		["@variable.builtin"] = { fg = c.blue },
		["@variable.parameter"] = { fg = c.magenta },
		["@constructor.javascript"] = { fg = c.cyan },
		["@keyword.clojure"] = { fg = c.bright_cyan },

		["@lsp.type.boolean"] = { link = "@boolean" },
		["@lsp.type.builtinType"] = { link = "@type.builtin" },
		["@lsp.type.comment"] = { link = "@comment" },
		["@lsp.type.enum"] = { link = "@type" },
		["@lsp.type.enumMember"] = { link = "@constant" },
		["@lsp.type.escapeSequence"] = { link = "@string.escape" },
		["@lsp.type.formatSpecifier"] = { link = "@punctuation.special" },
		["@lsp.type.interface"] = { fg = c.blue },
		["@lsp.type.keyword"] = { link = "@keyword" },
		["@lsp.type.namespace"] = { link = "@namespace" },
		["@lsp.type.number"] = { link = "@number" },
		["@lsp.type.operator"] = { link = "@operator" },
		["@lsp.type.parameter"] = { link = "@parameter" },
		["@lsp.type.property"] = { link = "@property" },
		["@lsp.type.selfKeyword"] = { link = "@variable.builtin" },
		["@lsp.type.string.rust"] = { link = "@string" },
		["@lsp.type.typeAlias"] = { link = "@type.definition" },
		["@lsp.typemod.class.defaultLibrary"] = { link = "@type.builtin" },
		["@lsp.typemod.enum.defaultLibrary"] = { link = "@type.builtin" },
		["@lsp.typemod.enumMember.defaultLibrary"] = { link = "@constant.builtin" },
		["@lsp.typemod.function.defaultLibrary"] = { link = "@function.builtin" },
		["@lsp.typemod.keyword.async"] = { link = "@keyword.coroutine" },
		["@lsp.typemod.macro.defaultLibrary"] = { link = "@function.builtin" },
		["@lsp.typemod.method.defaultLibrary"] = { link = "@function.builtin" },
		["@lsp.typemod.operator.injected"] = { link = "@operator" },
		["@lsp.typemod.string.injected"] = { link = "@string" },
		["@lsp.typemod.type.defaultLibrary"] = { fg = c.blue },
		["@lsp.typemod.variable.defaultLibrary"] = { link = "@variable.builtin" },
		["@lsp.typemod.variable.injected"] = { link = "@variable" },

		["@markup.heading"] = { fg = c.gray06, bold = true },
		["@markup.heading.1"] = { fg = c.gray06, bold = true, italic = true },
		["@markup.heading.1.marker"] = { link = "@comment" },
		["@markup.heading.2"] = { fg = c.gray06, bold = true, italic = true },
		["@markup.heading.2.marker"] = { link = "@comment" },
		["@markup.heading.3"] = { fg = c.gray06, bold = true, italic = true },
		["@markup.heading.3.marker"] = { link = "@comment" },
		["@markup.heading.4"] = { fg = c.gray06, bold = true, italic = true },
		["@markup.heading.4.marker"] = { link = "@comment" },
		["@markup.heading.5"] = { fg = c.gray06, bold = true, italic = true },
		["@markup.heading.5.marker"] = { link = "@comment" },
		["@markup.heading.6"] = { fg = c.gray06, bold = true, italic = true },
		["@markup.heading.6.marker"] = { link = "@comment" },
		["@markup.link"] = { fg = c.gray06 },
		["@markup.link.label"] = { fg = c.cyan },
		["@markup.link.url"] = { fg = c.blue },
		["@markup.list"] = { fg = c.gray05, bold = true },
		["@markup.list.checked"] = { fg = c.gray05 },
		["@markup.list.unchecked"] = { fg = c.gray05 },
		["@markup.raw.block"] = { fg = c.gray05 },
		["@markup.raw.delimiter"] = { fg = c.gray05 },
		["@markup.quote"] = { fg = c.gray06 },
		["@markup.strikethrough"] = { fg = c.gray04, strikethrough = true },
		["@punctuation.special.htmldjango"] = { link = "Special" },
		["@keyword.htmldjango"] = { link = "Keyword" },
		["@variable.htmldjango"] = { link = "Identifier" },
		["@function.call.htmldjango"] = { link = "Function" },
		["@string.htmldjango"] = { link = "String" },

		DiagnosticOk = { fg = c.green },
		DiagnosticError = { fg = c.red },
		DiagnosticWarn = { fg = c.yellow },
		DiagnosticInfo = { fg = c.blue },
		DiagnosticHint = { fg = c.cyan },
		DiagnosticUnderlineError = { fg = c.red, underline = true },
		DiagnosticUnderlineWarn = { fg = c.yellow, underline = true },
		DiagnosticUnderlineInfo = { fg = c.blue, underline = true },
		DiagnosticUnderlineHint = { fg = c.cyan, underline = true },

		LspReferenceWrite = { fg = c.blue, underline = true },
		LspReferenceText = { fg = c.blue, underline = true },
		LspReferenceRead = { fg = c.blue, underline = true },
		LspSignatureActiveParameter = { fg = c.yellow, bold = true },

		GitSignsAdd = { fg = c.green },
		GitSignsChange = { fg = c.yellow },
		GitSignsDelete = { fg = c.red },

		diffAdded = { fg = c.bright_green },
		diffRemoved = { fg = c.bright_red },
		diffChanged = { fg = c.bright_yellow },
		diffOldFile = { fg = c.gray04 },
		diffNewFile = { fg = c.white },
		diffFile = { fg = c.gray05 },
		diffLine = { fg = c.cyan },
		diffIndexLine = { fg = c.magenta },

		HopNextKey = { fg = c.bright_yellow },
		HopNextKey1 = { fg = c.bright_blue },
		HopNextKey2 = { fg = c.bright_cyan },
		HopUnmatched = { fg = c.gray04 },
		HopCursor = { fg = c.bright_cyan },
		HopPreview = { fg = c.bright_blue },

		CmpItemAbbrDeprecated = { fg = c.gray06, strikethrough = true },
		CmpItemAbbrMatch = { fg = c.blue, bold = true },
		CmpItemAbbrMatchFuzzy = { fg = c.blue, bold = true },
		CmpItemMenu = { fg = c.gray05 },
		CmpItemKindText = { fg = c.gray06 },
		CmpItemKindFunction = { fg = c.cyan },
		CmpItemKindVariable = { fg = c.bright_white },
		CmpItemKindEnum = { fg = c.green },
		CmpItemKindSnippet = { fg = c.yellow },

		NavicIconsFile = { fg = c.fg, bg = c.none },
		NavicIconsModule = { fg = c.yellow, bg = c.none },
		NavicIconsNamespace = { fg = c.fg, bg = c.none },
		NavicIconsPackage = { fg = c.fg, bg = c.none },
		NavicIconsClass = { fg = c.cyan, bg = c.none },
		NavicIconsMethod = { fg = c.blue, bg = c.none },
		NavicIconsProperty = { fg = c.green, bg = c.none },
		NavicIconsField = { fg = c.green, bg = c.none },
		NavicIconsConstructor = { fg = c.cyan, bg = c.none },
		NavicIconsEnum = { fg = c.cyan, bg = c.none },
		NavicIconsInterface = { fg = c.cyan, bg = c.none },
		NavicIconsFunction = { fg = c.blue, bg = c.none },
		NavicIconsVariable = { fg = c.magenta, bg = c.none },
		NavicIconsConstant = { fg = c.magenta, bg = c.none },
		NavicIconsString = { fg = c.green, bg = c.none },
		NavicIconsNumber = { fg = c.cyan, bg = c.none },
		NavicIconsBoolean = { fg = c.yellow, bg = c.none },
		NavicIconsArray = { fg = c.gray06, bg = c.none },
		NavicIconsObject = { fg = c.gray06, bg = c.none },
		NavicIconsKey = { fg = c.blue, bg = c.none },
		NavicIconsKeyword = { fg = c.blue, bg = c.none },
		NavicIconsNull = { fg = c.cyan, bg = c.none },
		NavicIconsEnumMember = { fg = c.green, bg = c.none },
		NavicIconsStruct = { fg = c.cyan, bg = c.none },
		NavicIconsEvent = { fg = c.cyan, bg = c.none },
		NavicIconsOperator = { fg = c.fg, bg = c.none },
		NavicIconsTypeParameter = { fg = c.green, bg = c.none },
		NavicText = { fg = c.white, bg = c.none },
		NavicSeparator = { fg = c.gray06, bg = c.none },

		NotifyBackground = { fg = c.white, bg = c.bg },
		NotifyERRORBorder = { fg = c.red, bg = cfg.transparent and c.none or c.bg },
		NotifyWARNBorder = { fg = c.yellow, bg = cfg.transparent and c.none or c.bg },
		NotifyINFOBorder = { fg = c.blue, bg = cfg.transparent and c.none or c.bg },
		NotifyDEBUGBorder = { fg = c.gray06, bg = cfg.transparent and c.none or c.bg },
		NotifyTRACEBorder = { fg = c.cyan, bg = cfg.transparent and c.none or c.bg },
		NotifyERRORIcon = { fg = c.bright_red },
		NotifyWARNIcon = { fg = c.bright_yellow },
		NotifyINFOIcon = { fg = c.bright_blue },
		NotifyDEBUGIcon = { fg = c.gray05 },
		NotifyTRACEIcon = { fg = c.bright_cyan },
		NotifyERRORTitle = { fg = c.bright_red },
		NotifyWARNTitle = { fg = c.bright_yellow },
		NotifyINFOTitle = { fg = c.bright_blue },
		NotifyDEBUGTitle = { fg = c.gray05 },
		NotifyTRACETitle = { fg = c.bright_cyan },
		NotifyERRORBody = { fg = c.white, bg = cfg.transparent and c.none or c.bg },
		NotifyWARNBody = { fg = c.white, bg = cfg.transparent and c.none or c.bg },
		NotifyINFOBody = { fg = c.white, bg = cfg.transparent and c.none or c.bg },
		NotifyDEBUGBody = { fg = c.white, bg = cfg.transparent and c.none or c.bg },
		NotifyTRACEBody = { fg = c.white, bg = cfg.transparent and c.none or c.bg },

		NeoTreeFloatBorder = { fg = c.gray03, bg = c.bg },
		NeoTreeFloatTitle = { fg = c.gray05, bg = c.gray07 },
		NeoTreeTitleBar = { fg = c.gray05, bg = c.gray01 },

		TelescopeBorder = { fg = c.cyan, bg = cfg.transparent and c.none or c.gray02 },
		TelescopeNormal = { fg = c.fg, bg = cfg.transparent and c.none or c.gray02 },
		TelescopePreviewTitle = { fg = c.fg, bg = cfg.transparent and c.none or c.cyan, bold = true },
		TelescopeResultsTitle = { fg = c.fg, bg = cfg.transparent and c.none or c.cyan, bold = true },
		TelescopePromptTitle = { fg = c.fg, bg = cfg.transparent and c.none or c.cyan, bold = true },
		TelescopePromptBorder = { fg = c.cyan, bg = cfg.transparent and c.none or c.gray01 },
		TelescopePromptNormal = { fg = c.gray06, bg = cfg.transparent and c.none or c.gray01 },
		TelescopePromptCounter = { fg = c.gray04, bg = cfg.transparent and c.none or c.gray01 },
		TelescopeMatching = { fg = c.yellow, underline = true },

		DapUINormal = { link = "Normal" },
		DapUIVariable = { link = "Normal" },
		DapUIScope = { fg = c.blue },
		DapUIType = { fg = c.magenta },
		DapUIValue = { link = "Normal" },
		DapUIModifiedValue = { fg = c.blue, bold = true },
		DapUIDecoration = { fg = c.blue },
		DapUIThread = { fg = c.bright_green },
		DapUIStoppedThread = { fg = c.blue },
		DapUIFrameName = { link = "Normal" },
		DapUISource = { fg = c.magenta },
		DapUILineNumber = { fg = c.blue },
		DapUIFloatNormal = { link = "NormalFloat" },
		DapUIFloatBorder = { fg = c.blue },
		DapUIWatchesEmpty = { fg = c.bright_cyan },
		DapUIWatchesValue = { fg = c.bright_green },
		DapUIWatchesError = { fg = c.bright_cyan },
		DapUIBreakpointsPath = { fg = c.blue },
		DapUIBreakpointsInfo = { fg = c.bright_green },
		DapUIBreakpointsCurrentLine = { fg = c.bright_green, bold = true },
		DapUIBreakpointsLine = { link = "DapUILineNumber" },
		DapUIBreakpointsDisabledLine = { fg = c.gray03 },
		DapUICurrentFrameName = { link = "DapUIBreakpointsCurrentLine" },
		DapUIStepOver = { fg = c.blue },
		DapUIStepInto = { fg = c.blue },
		DapUIStepBack = { fg = c.blue },
		DapUIStepOut = { fg = c.blue },
		DapUIStop = { fg = c.bright_cyan },
		DapUIPlayPause = { fg = c.bright_green },
		DapUIRestart = { fg = c.bright_green },
		DapUIUnavailable = { fg = c.gray03 },
		DapUIWinSelect = { fg = c.cyan, bold = true },
		DapUIEndofBuffer = { link = "EndofBuffer" },

		FlashBackdrop = { link = "Comment" },
		FlashCurrent = { link = "IncSearch" },
		FlashCursor = { bg = c.bright_blue, fg = c.bg_dark, bold = true },
		FlashLabel = { bg = c.cyan, bold = true, fg = c.bg_dark },
		FlashMatch = { link = "Search" },
		FlashPrompt = { link = "MsgArea" },
		FlashPromptIcon = { link = "Special" },

		IlluminatedWordText = { bg = c.gray03 },
		IlluminatedWordRead = { bg = c.gray03 },
		IlluminatedWordWrite = { bg = c.gray03 },

		YankHighlight = { bg = c.magenta, fg = c.bg },
	}

	for name, val in pairs(hl) do
		vim.api.nvim_set_hl(0, name, val)
	end
end

function M.load()
	vim.cmd("hi clear")
	if vim.fn.exists("syntax_on") then
		vim.cmd("syntax reset")
	end
	vim.o.termguicolors = true
	vim.g.colors_name = "groob"

	set_terminal_colors()
	set_groups()
end

return M
